### ISSUE TITLE
Question: errors using .pde from pde_staging.

### ISSUE THREAD

**Issue by fredguth** [hype/HYPE_Processing#120]
I have found some difficulties by using HYPE.pde as the error message is always on the same line :-)

So, I thought of downloading the pde files from pde_staging and running from there to find where are the errors I am finding.  

The problem is that I can't run most pde files.  I get lots of errors like:
`HCanvas.pde:11:0:11:0: The return types are incompatible for the inherited methods Iterable<build.HDrawable>.iterator(), build.HDrawable.iterator()`

That is not the only .pde file with incompatible types.  Is it right to use the pde files like this?  I have also tried to include HYPE.jar and also the unzipped hype folder in documents/processing but it didn't work.

Can someone help?

**Comment by hype** [comment]
this was fixed here... https://github.com/hype/HYPE_Processing/issues/95

it's because Processing has updated to version 3 - and caused errors in HYPE.pde relating to the HCanvas class - since then we've moved to a proper HYPE library - master branch which fixes this issue.

download HYPE from master :+1: 
https://github.com/hype/HYPE_Processing

in distribution unzip HYPE.zip and place in your /documents/processing/libraries folder... check examples for new imports... no need to use HYPE.pde anymore.

hope this helps,

**Comment by fredguth** [comment]
Will try.  Thanks.
