### ISSUE TITLE
Documentation enhancement: Find your libraries location on linux

### ISSUE THREAD

**Issue by bryanmaina** [hype/HYPE_Processing#137]
To find the folder where you should to copy HYPE folder I find easier to just 
1) open the file "~/.processing/preferences.txt"
2) find the line "sketchbook.path.three=/some/folder"

The sub-folder "/libraries/" in that folder("/some/folder") is where your custom libraries or those downloaded by the processing editors are.
In my case it wasn't the folder " ~/Documents/Processing". It can be anything you specified when you started your processing editor for the first time.

I think this should be added to the documentation because it took me a good hour to figure out what was happening.

**This is how it works on my Arch Linux installation at least.**

**Comment by GoToLoop** [comment]
Open any sketch. Hit CTRL+K. The sketchbook path is 1 directory up.

**Comment by aemb** [comment]
That's a nice command to find them and editing them but it doesn't show the path on my system. It opens a window with the content of the sketchbook.
After doing what you said I have to go to the tab; click "File" then click on "Open Recent" in order to see the path.

This is better if don't mind to have to remember which file you should to search inside :) I wish I knew this before.  You also have to make sure that at least one sketch is saved in your sketchbook in order to make one of those appears in the recent files.
