### ISSUE TITLE
 _graphics.clear();

### ISSUE THREAD

**Issue by ashleyjamesbrown** [hype/HYPE_Processing#76]
the function clear() does not exist ?

**Comment by tracerstar** [comment]
Hi Ashley,

The function clear() should be fine, as per Processing's documentation: https://processing.org/reference/clear_.html

I'm guessing by your second comment you might have been trying to use HYPE with Processing 1.5? I think HYPE was specifically built with Processing 2 in mind, so probably isn't backwards compatible.

If you're still having a problem with clear() and HYPE, let us know, otherwise I'm closing this as a non issue.

Thanks,
Ben.
